name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build:client
      - run: npm ci
      - run: npm test

      - name: Update package.json with release version
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version change
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: update package.json to version ${{ github.event.release.tag_name }}"

      # Find the branch that the tag is based on
      - name: Get branch name
        id: get_branch
        run: |
          BRANCH_NAME=$(git branch -r --contains tags/${{ github.ref_name }} | grep -Eo 'origin/[^ ]+$' | sed 's|origin/||')
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Push changes
        if: success()
        run: git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
